stages:
  - deploy
  - docker

docker:
  stage: docker
  image: docker:stable
  only: 
    - master
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -f docker/DockerFile -t registry.iop-ventures.com/iop-stack/infrastructure/developer-portal/doc:latest .
    - docker push registry.iop-ventures.com/iop-stack/infrastructure/developer-portal/doc
    
# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master