///###TS_STEP_1
// Import the necessary modules from our SDK
import { Crypto, Layer1, Layer2, Network, NetworkConfig } from '@internet-of-people/sdk';
///###TS_STEP_1

///###TS_STEP_2
// Select the testnet
export const network = Network.Testnet;

// These details give access to a pre-generated account that pay the gas for the transaction.
export const hydraGasPassphrase = "scout try doll stuff cake welcome random taste load town clerk ostrich";
export const hydraGasPublicKey = "03d4bda72219264ff106e21044b047b6c6b2c0dde8f49b42c848e086b97920adbf";
export const unlockPassword = '+*7=_X8<3yH:v2@s';
///###TS_STEP_2

///###TS_STEP_3
// YOU HAVE TO SAVE THE PASSPHRASE SECURELY!
const phrase = new Crypto.Bip39('en').generate().phrase;

// Creates a new vault based on the BIP39 passphrase, password and unlock password
const vault = Crypto.Vault.create(
  phrase,
  '8qjaX^UNAafDL@!#',   // The 25th word of the passphrase
  unlockPassword,       // Encrypts the master seed
);
///###TS_STEP_3

///###TS_STEP_4
// Initialize the Morpheus plugin on your personal vault:
Crypto.MorpheusPlugin.init(vault, unlockPassword);
const morpheus = Crypto.MorpheusPlugin.get(vault);

// Selects the first DID
const did = morpheus.pub.personas.did(0);
console.log("Using DID: ", did.toString());
///###TS_STEP_4

if(!did) {
    throw new Error('DID is null');
}

///###TS_STEP_5
// Acquire the default key
const keyId = did.defaultKeyId();

// The contract details
const contractStr = "A long legal document, e.g. a contract with all details";
const contractBytes = new Uint8Array(Buffer.from(contractStr));

// Acquire the plugin's private interface that provides you the sign interface
const morpheusPrivate = morpheus.priv(unlockPassword); 

// The signed contract, which you need to store securely!
const signedContract = morpheusPrivate.signDidOperations(keyId, contractBytes);
console.log("Signed contract:", JSON.stringify({
    content: Buffer.from(signedContract.content).toString('utf8'),
    publicKey: signedContract.publicKey.toString(),
    signature: signedContract.signature.toString(),
}, null, 2));
///###TS_STEP_5

///###TS_STEP_6
// The beforeProof (a.k.a. Proof of Existence) is generated by hashing the signed contract
const beforeProof = Crypto.digestJson(signedContract);
console.log("Proof of Existence:", beforeProof);
///###TS_STEP_6

if(!beforeProof) {
    throw new Error('beforeProof is null');
}

(async () => {
///###TS_STEP_7
// Create our operation attempts data structure
const opAttempts = new Layer1.OperationAttemptsBuilder()
    .registerBeforeProof(beforeProof)
    .getAttempts();

// Initialize our Layer-1 API
const layer1Api = await Layer1.createApi(NetworkConfig.fromNetwork(network));

// Query and increment the current nonce of the owner of the tx fee
let nonce = await layer1Api.getWalletNonce(hydraGasPublicKey);
nonce = nonce.valueOf() + BigInt(1);

// Now you are ready to send the transaction
const txId = await layer1Api.sendMorpheusTxWithPassphrase(opAttempts, hydraGasPassphrase, nonce);
console.log("Transaction ID: ", txId);
///###TS_STEP_7

///###TS_STEP_8
// Block confirmation time
const waitUntil12Sec = (): Promise<void> => {
    return new Promise((resolve) => {
        return setTimeout(resolve, 12*1000);
    });
};
await waitUntil12Sec();

// Layer-1 transaction must be confirmed
let txStatus = await layer1Api.getTxnStatus(txId);
console.log("Tx status:", txStatus.get());

// Initialize the Layer-2 Morpheus API to query the transaction status
const layer2MorpheusApi = await Layer2.createMorpheusApi(NetworkConfig.fromNetwork(network));
let ssiTxStatus = await layer2MorpheusApi.getTxnStatus(txId);
console.log("SSI Tx status:", ssiTxStatus.get());
///###TS_STEP_8

///###TS_STEP_9
// We assume that signedContract is in scope and available
const expectedContentId = Crypto.digestJson(signedContract);
///###TS_STEP_9

///###TS_STEP_10
// Query the blockchain for the hash of the signed contract (Proof of Existence)
const history = await layer2MorpheusApi.getBeforeProofHistory(expectedContentId);
console.log("Proof history:", history);
///###TS_STEP_10

if(history.contentId !== expectedContentId) {
    throw new Error('Content Id does not match');
}

})().catch((e)=>{
    process.stderr.write(e.message);
    process.exit(1);
});
