version: '2'
services:
  nginx:
    image: 'registry.iop-ventures.com/iop-stack/developer-portal/developer-portal:latest'
    container_name: nginx
    networks:
      - core
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "80:80"

networks:
  core:
